version: '3'
services:
  api:
    build:
      context: api
    env_file:
      - oauth/secret.env
      - api/dev.env
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
  nginx:
    build: nginx/dev
    restart: always
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web-app:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./web-app
    depends_on:
      - api
    volumes:
      - ./web-app/src:/cinside/src
      - ./web-app/public:/cinside/public
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  mongo:
  rabbitmq-data:
