micronaut:
  application:
    name: api
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${OAUTH_CLIENT_ID:xxx}
          client-secret: ${OAUTH_CLIENT_SECRET:yyy}
          openid:
            issuer: 'https://accounts.google.com'
      login-uri: "/api/oauth/login{/provider}"
      callback-uri: "/api/oauth/callback{/provider}"
    endpoints:
      logout:
        get-allowed: true
        path: "/api/logout"
    redirect:
      login-failure: ${REGISTRATION_PAGE}
netty:
  default:
    allocator:
      max-order: 3
db:
  name: "cinside"
  personCollection: "person"
mongodb:
  uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:example}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}
