micronaut:
  application:
    name: api
  server:
    cors:
      enabled: true
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${OAUTH_CLIENT_ID:xxx}
          client-secret: ${OAUTH_CLIENT_SECRET:yyy}
          openid:
            issuer: 'https://accounts.google.com'
      login-uri: "/api/oauth/login{/provider}"
      callback-uri: "/api/oauth/callback{/provider}"
    endpoints:
      logout:
        get-allowed: true
        path: "/api/logout"
    redirect:
      login-failure: "/sign-up"
      login-success: "/sign-in-succeeded"
      logout: "/logout-succeeded"
    token:
      jwt:
        claims-validators:
          expiration: false
netty:
  default:
    allocator:
      max-order: 3
db:
  name: "cinside"
  personCollection: "person"
  projectCollection: "project"
mongodb:
  uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:example}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}
rabbitmq:
  host: rabbitmq
